### ISSUE TITLE
Cannot compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by onselakin** [scylladb/seastar#150]
Here is the output of ninja:

[2/155] CXX build/release/tests/output_stream_test.o
FAILED: g++ -MMD -MT build/release/tests/output_stream_test.o -MF build/release/tests/output_stream_test.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I.   -DHAVE_HWLOC -DHAVE_NUMA -O2 -I build/release/gen -c -o build/release/tests/output_stream_test.o tests/output_stream_test.cc
In file included from ./core/reactor.hh:52:0,
                 from tests/output_stream_test.cc:24:
./core/posix.hh: In member function ‘boost::optional<long int> file_desc::recv(void_, size_t, int)’:
./core/posix.hh:191:20: error: converting to ‘boost::optional<long int>’ from initializer list would use explicit constructor ‘boost::optional<T>::optional(Expr&&, typename boost::disable_if_c<((boost::is_base_of<boost::optional_detail::optional_tag, typename boost::decay<Expr>::type>::value) || boost::is_same<typename boost::decay<Expr>::type, boost::none_t>::value)>::type_) [with Expr = long int&; T = long int; typename boost::disable_if_c<((boost::is_base_of<boost::optional_detail::optional_tag, typename boost::decay<Expr>::type>::value) || boost::is_same<typename boost::decay<Expr>::type, boost::none_t>::value)>::type = void]’
         return { r };
                    ^
[2/155] CXX build/release/apps/memcached/memcache.o
FAILED: g++ -MMD -MT build/release/apps/memcached/memcache.o -MF build/release/apps/memcached/memcache.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I.   -DHAVE_HWLOC -DHAVE_NUMA -O2 -I build/release/gen -c -o build/release/apps/memcached/memcache.o apps/memcached/memcache.cc
In file included from ./core/reactor.hh:52:0,
                 from ./core/future-util.hh:27,
                 from apps/memcached/memcache.cc:30:
./core/posix.hh: In member function ‘boost::optional<long int> file_desc::recv(void_, size_t, int)’:
./core/posix.hh:191:20: error: converting to ‘boost::optional<long int>’ from initializer list would use explicit constructor ‘boost::optional<T>::optional(Expr&&, typename boost::disable_if_c<((boost::is_base_of<boost::optional_detail::optional_tag, typename boost::decay<Expr>::type>::value) || boost::is_same<typename boost::decay<Expr>::type, boost::none_t>::value)>::type_) [with Expr = long int&; T = long int; typename boost::disable_if_c<((boost::is_base_of<boost::optional_detail::optional_tag, typename boost::decay<Expr>::type>::value) || boost::is_same<typename boost::decay<Expr>::type, boost::none_t>::value)>::type = void]’
         return { r };
                    ^
ninja: build stopped: subcommand failed.

**Comment by onselakin** [comment]
Tried compiling without without --compiler=g++-4.9 to no avail so switched to Ubuntu 14.04. Successfully compiled after dealing with a few gcc and Ubuntu related problems.

**Comment by avikivity** [comment]
We do want to build on 16.04, so far I'm tracking https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71147 (gcc 6).  What gcc did you use?  This doesn't seem to be the same error.

**Comment by onselakin** [comment]
I really can't recall at the moment but I do remember manually installing almost all of the dependencies. I guess that's something to do with Ubuntu itself because I couldn't get the dependencies with apt-get and had to use aptitude instead.

I was just going to go through the building process on Ubuntu 16.04 again to provide further information but everything went smooth until I bumped into [this](https://github.com/scylladb/seastar/issues/122).

Now I'm getting `-fsanitize=vptr is broken, disabling` after I remove the gcc++-4.9 option while configuring.

**Comment by avikivity** [comment]
`-fsanitize=vptr is broken, disabling` is informational and expected. Maybe we should prefix it with `note:`.  I'll look at #122.

**Comment by xemul** [comment]
gcc-4 no longer supported
