### PR TITLE
build: do not error when run into GCC BZ-1017852

### LINKED ISSUE #1716: Seastar cannot be compiled with gcc 13.1 and fmt lib version 10
```
In static member function ‘static constexpr _Up* std::__copy_move<_IsMove, true, std::random_access_iterator_tag>::__copy_m(_Tp*, _Tp*, _Up*) [with _Tp = unsigned int; _Up = unsigned int; bool _IsMove = false]’,
    inlined from ‘constexpr _OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = unsigned int*; _OI = unsigned int*]’ at /usr/include/c++/13/bits/stl_algobase.h:506:30,
    inlined from ‘constexpr _OI std::__copy_move_a1(_II, _II, _OI) [with bool _IsMove = false; _II = unsigned int*; _OI = unsigned int*]’ at /usr/include/c++/13/bits/stl_algobase.h:533:42,
    inlined from ‘constexpr _OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = unsigned int*; _OI = unsigned int*]’ at /usr/include/c++/13/bits/stl_algobase.h:540:31,
    inlined from ‘constexpr _OI std::copy(_II, _II, _OI) [with _II = unsigned int*; _OI = unsigned int*]’ at /usr/include/c++/13/bits/stl_algobase.h:633:7,
    inlined from ‘static _ForwardIterator std::__uninitialized_copy<true>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = unsigned int*; _ForwardIterator = unsigned int*]’ at /usr/include/c++/13/bits/stl_uninitialized.h:147:27,
    inlined from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = unsigned int*; _ForwardIterator = unsigned int*]’ at /usr/include/c++/13/bits/stl_uninitialized.h:185:15,
    inlined from ‘constexpr void fmt::v9::basic_memory_buffer<T, SIZE, Allocator>::grow(size_t) [with T = unsigned int; long unsigned int SIZE = 32; Allocator = std::allocator<unsigned int>]’ at /usr/include/fmt/format.h:925:26,
    inlined from ‘constexpr void fmt::v9::detail::buffer<T>::try_reserve(size_t) [with T = unsigned int]’ at /usr/include/fmt/core.h:928:39,
    inlined from ‘constexpr void fmt::v9::detail::buffer<T>::try_reserve(size_t) [with T = unsigned int]’ at /usr/include/fmt/core.h:927:24,
    inlined from ‘constexpr void fmt::v9::detail::buffer<T>::try_resize(size_t) [with T = unsigned int]’ at /usr/include/fmt/core.h:919:16,
    inlined from ‘constexpr void fmt::v9::basic_memory_buffer<T, SIZE, Allocator>::resize(size_t) [with T = unsigned int; long unsigned int SIZE = 32; Allocator = std::allocator<unsigned int>]’ at /usr/include/fmt/format.h:897:63,
    inlined from ‘constexpr void fmt::v9::detail::bigint::assign(UInt) [with UInt = long unsigned int; typename std::enable_if<(std::is_same<UInt, long unsigned int>::value || std::is_same<UInt, __int128 unsigned>::value), int>::type <anonymous> = 0]’ at /usr/include/fmt/format.h:2792:19,
    inlined from ‘constexpr void fmt::v9::detail::bigint::operator=(Int) [with Int = int]’ at /usr/include/fmt/format.h:2813:11,
    inlined from ‘constexpr void fmt::v9::detail::bigint::assign_pow10(int)’ at /usr/include/fmt/format.h:2886:32:
/usr/include/c++/13/bits/stl_algobase.h:437:30: error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ writing between 5 and 9223372036854775807 bytes into a region of size 4 overflows the destination [-Werror=stringop-overflow=]
  437 |             __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/13/x86_64-redhat-linux/bits/c++allocator.h:33,
                 from /usr/include/c++/13/bits/allocator.h:46,
                 from /usr/include/c++/13/string:43:

```

Can be reduced to https://godbolt.org/z/osqjxs8Wq

The issue seems to be worked around in fmt's master

Relevant discussion https://github.com/fmtlib/fmt/issues/3382

Reading quickly through it, they seem to have traced it to changes in implicit move rules, described in https://gcc.gnu.org/gcc-13/porting_to.html

### PR DESCRIPTION
**Pull request by tchaikov**
if the compiler impacted by
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=107852 is used to compile Seastar with fmtlib v10, the tree would fail to compile, because we consider `-Warray-bounds` warnings as error.

to build with compiler (typically GCC 13.1) which suffers from this bug. let's stop considering these false alarms as error. a minimal reproducer is introduced for testing this compiler bug.

Fixes #1716
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
tested using

```console
$ echo 'docker run --pids-limit -1 --security-opt seccomp=unconfined --network host --userns=keep-id -v $PWD:$PWD:z -w $PWD  docker.io/scylladb/seastar-toolchain:2023-11-02 "$@"' > run
$ ./run ./configure.py --compiler g++-13 --mode release
$ ./run ninja -C build/release  
```

**Comment by tchaikov** [comment]
@scylladb/seastar-maint hello maintainers, could you help review this change?

File: cmake/CheckGcc107852.cmake [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+
+int main() {
+    float grades[] = {3.14};
+    fmt::print(\"{}\", grades);
+}"
+  Cxx_Compiler_BZ107852_Free
+  FAIL_REGEX "is out of the bounds")
+
+cmake_pop_check_state ()
+
```
Comment (avikivity) [inline cmake/CheckGcc107852.cmake:24]: Suggest to use the reproducer in the bug itself, so we don't catch it because of some unrelated problem (like missing headers).

Comment (tchaikov) [reply cmake/CheckGcc107852.cmake:24]: > reproducer fails for unrelated reason

i use `FAIL_REGEX "is out of the bounds"` to ensure that this does not happen.
