### ISSUE TITLE
io_tester app fails to compile with GCC 5

### ISSUE THREAD

**Issue by argenet** [scylladb/seastar#364]
io_tester fails to compile on Ubuntu 16.04 with GCC 5:

g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

[7/231] CXX build/release/apps/io_tester/io_tester.o
FAILED: g++ -MD -MT build/release/apps/io_tester/io_tester.o -MF build/release/apps/io_tester/io_tester.o.d -O2 -I/home/marek/wan/xwan/seastar/build/release/gen -I/home/marek/wan/xwan/seastar/build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/home/marek/wan/xwan/seastar -U_FORTIFY_SOURCE  -I/home/marek/wan/xwan/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-sign-compare -Wno-error=cpp -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/apps/io_tester/io_tester.o apps/io_tester/io_tester.cc
apps/io_tester/io_tester.cc: In lambda function:
apps/io_tester/io_tester.cc:172:56: error: ‘request_type’ is not a class, namespace, or enumeration
                                 if ((request_type() == request_type::append) && (pos > _last_pos)) {

It compiles file with GCC 7.2 on Fedora 27.
