### ISSUE TITLE
can't compile on ubuntu 14.04

### ISSUE THREAD

**Issue by senior7515** [scylladb/seastar#63]
# OS: 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

# Error

```
FAILED: g++ -MMD -MT build/debug/core/reactor.o -MF build/debug/core/reactor.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined  -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -I build/debug/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -DHAVE_DPDK -I/home/agallego/workspace/seastar/build/dpdk/include -march=native -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_MACHINE_CPUFLAG_AES -DRTE_MACHINE_CPUFLAG_PCLMULQDQ -DRTE_MACHINE_CPUFLAG_AVX -DRTE_MACHINE_CPUFLAG_RDRAND -DRTE_MACHINE_CPUFLAG_FSGSBASE -DRTE_MACHINE_CPUFLAG_F16C -DRTE_MACHINE_CPUFLAG_AVX2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2,RTE_CPUFLAG_AES,RTE_CPUFLAG_PCLMULQDQ,RTE_CPUFLAG_AVX,RTE_CPUFLAG_RDRAND,RTE_CPUFLAG_FSGSBASE,RTE_CPUFLAG_F16C,RTE_CPUFLAG_AVX2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof  -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -c -o build/debug/core/reactor.o core/reactor.cc
core/reactor.cc:52:27: fatal error: xfs/xfs_types.h: No such file or directory
 #include <xfs/xfs_types.h>
```

# Steps taken to fix:

1. Installed xfslibs-dev

```
$ sudo aptitude install xfslibs-dev 
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.

```

# Cannot find xfs_types.h

```
$ sudo find / -type f -name xfs_types.h  
```

**Comment by tweej** [comment]
Possibly related to: http://oss.sgi.com/cgi-bin/gitweb.cgi?p=xfs/cmds/xfsprogs.git;a=commit;h=b75ef5e7785869e44d6ac955cb1d07532f8dd003

**Comment by senior7515** [comment]
@tweej  yeah, looks like. :( same result. Too bad. It looks like ubuntu 15.04 has the right pkgs - from the issue list in this repo.

**Comment by tweej** [comment]
As a workaround, you can modify the Trusty source package to include the headers:

> apt-get source xfslibs-dev
> Change include/Makefile to do under install-dev: default (add QAHFILES):
> 	$(INSTALL) -m 644 $(QAHFILES) $(HFILES) $(PKG_INC_DIR)
> sudo apt-get install build-dep xfslibs-dev
> sudo apt-get install devscripts; debuild -b -uc -us
> Then install the created package. Mine was xfslibs-dev_3.1.9ubuntu2_amd64.deb.

**Comment by tweej** [comment]
As a workaround, you can modify the Trusty source package to include the headers:

> apt-get source xfslibs-dev; cd xfsprogs*
> Change include/Makefile to do under install-dev: default (add QAHFILES):
> 	$(INSTALL) -m 644 $(QAHFILES) $(HFILES) $(PKG_INC_DIR)
> sudo apt-get install build-dep xfslibs-dev
> sudo apt-get install devscripts; debuild -b -uc -us
> Then install the created package from the parent directory. Mine was xfslibs-dev_3.1.9ubuntu2_amd64.deb.

**Comment by avikivity** [comment]
@tweej, can you file a bug with Ubuntu to fix their headers?

**Comment by ckamm** [comment]
@avikivity Note that on my Ubuntu 14.04 reactor.cc compiled fine with the xfs_types.h include removed. I don't see any of its defines used in 16cdd7530249d5e62085dbc571af5b95d855f724, at least when looking casually. Maybe the include is not needed?

**Comment by senior7515** [comment]
@ckamm @tweej  @avikivity - FYI. i just compiled successfully on ubuntu 14.04 by commenting line 52 on the reactor.cc as suggested.

**Comment by avikivity** [comment]
It's needed on Fedora.

**Comment by avikivity** [comment]
Maybe it can be replaced with `xfs/xfs.h`?

**Comment by senior7515** [comment]
@avikivity I just tested this change and it works (it compiles) too.

```
//#include <xfs/xfs_types.h>
//#include <xfs/xfs_fs.h>
#include <xfs/xfs.h>
```

**Comment by ckamm** [comment]
@avikivity Did you test `xfs/xfs.h` on Fedora? It works for me too.

**Comment by avikivity** [comment]
It should work, please post a patch.

**Comment by tweej** [comment]
Oh cool. Submitted Ubuntu bug anyway: https://bugs.launchpad.net/ubuntu/+source/xfsprogs/+bug/1505462

**Comment by senior7515** [comment]
Looks like @ckamm put in a fix here: 3eb06eecc3774b323fb5c2d8d4ca63b2789198ee

Closing! thanks guys!
