### ISSUE TITLE
Seastar fails to build on gcc 11.1.1

### ISSUE THREAD

**Issue by nyh** [scylladb/seastar#914]
When building Seastar on Fedora 34 with gcc 11.1.1 (in gnu++17 mode) and c-ares 1.17.1, I get several build errors like the following in `src/net/dns.cc`:

```
../../src/net/dns.cc: In static member function ‘static void seastar::net::dns_r
esolver::impl::get_srv_records(seastar::net::dns_resolver::srv_proto, const sstr
ing&, const sstring&)::<lambda(void*, int, int, unsigned char*, int)>::_FUN(void
*, int, int, unsigned char*, int)’:
../../src/net/dns.cc:361:9: error: ‘this’ pointer is null [-Werror=nonnull]
  361 |         }, reinterpret_cast<void *>(p.release()));
      |         ^
```

**Comment by nyh** [comment]
It appears that this is a false alarm described in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96003.
I'm now looking how to work around this.
