### ISSUE TITLE
Failure to build on g++-4.9 @

### ISSUE THREAD

**Issue by jaypipes** [scylladb/seastar#122]
After pulling in the fix for Issue #121, I get a new build failure with g++ unable to determine reference to boost::program_options::options_description:

```
[90/266] LINK (stripped) build/debug/tests/allocator_test
FAILED: g++-4.9  -fsanitize=address -fsanitize=leak -fsanitize=undefined  -DASAN_ENABLED -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -I build/debug/gen -s -g -Wl,--no-as-needed   -fvisibility=hidden -pthread  -o build/debug/tests/allocator_test build/debug/tests/allocator_test.o build/debug/core/memory.o build/debug/core/posix.o -laio -lboost_program_options -lboost_system -lboost_filesystem -lstdc++ -lm -lboost_unit_test_framework -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -lxenstore -lhwloc -lnuma -lpciaccess -lxml2 -lz -lasan -lubsan 
build/debug/tests/allocator_test.o: In function `main':
/home/jaypipes/repos/seastar/tests/allocator_test.cc:76: undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
build/debug/tests/allocator_test.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int)':
/usr/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
<snip>
```

**Comment by karlbohlmark** [comment]
Building on ubuntu 16.04 yields a very similar error (undefined reference to boost::program_options::options_description) when linking httpd

**Comment by jaypipes** [comment]
Yeah, I haven't been able to get past this issue unfortunately :(

**Comment by karlbohlmark** [comment]
Actually this worked just fine on ubuntu 16.04 when I configured without --compiler=g++-4.9 and just used the default gcc version (6.0)

**Comment by dorlaor** [comment]
Good to know, it's way better this way

**Comment by xemul** [comment]
g++4.9 not supported any longer
