### ISSUE TITLE
undefined reference to `seastar::internal::seastar_logger' error on __aarch64__

### ISSUE THREAD

**Issue by andrzej-jackowski-scylladb** [scylladb/seastar#3021]
Seastar compilation fails on ARM platform. 

Example error message (from https://jenkins.scylladb.com/job/scylla-master/job/next/9704/changes):

```
21:45:23  FAILED: apps/iotune/iotune 
21:45:23  : && /usr/local/sbin/clang++ -O2 -Xlinker --dependency-file=apps/iotune/CMakeFiles/app_iotune.dir/link.d apps/iotune/CMakeFiles/app_iotune.dir/iotune.cc.o -o apps/iotune/iotune  -Wl,-rpath,/jenkins/workspace/scylla-master/next/scylla/build/dev/seastar  /usr/lib64/libyaml-cpp.so  libseastar.so  /usr/lib64/libboost_program_options.so.1.83.0  /usr/lib64/libcares.so  /usr/lib64/libfmt.so.11.1.4  /usr/lib64/liblz4.so && :
21:45:23  /usr/sbin/ld: libseastar.so: undefined reference to `seastar::internal::seastar_logger'
21:45:23  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
21:45:23  ninja: build stopped: subcommand failed.
```

The issue was introduced in https://github.com/scylladb/seastar/pull/3004/commits/520a36ed30e75a22d599db2ed2b2fccf54b81230.

`extern logger seastar_logger;` should be in `seastar`, not `seastar::internal` namespace
