### ISSUE TITLE
failed to configure from master on Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by mikhail-barg** [scylladb/seastar#771]
I'm just making my first steps with seastar, and already stumbled ( I'm doing steps from readme, namely:
> ./install-dependencies.sh
which finishes with no errors
and
> ./configure.py --mode=release
which gives me

> 
> ...
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
> -- Checking for module 'libcares'
> --   Found libcares, version 1.14.0
> -- Found c-ares: /usr/lib/x86_64-linux-gnu/libcares.so (found suitable version "1.14.0", minimum required is "1.13")
> -- Found cryptopp: /usr/lib/x86_64-linux-gnu/libcryptopp.so (Required is at least version "5.6.5")
> -- Could NOT find dpdk (missing: dpdk_INCLUDE_DIR dpdk_PMD_VMXNET3_UIO_LIBRARY dpdk_PMD_I40E_LIBRARY dpdk_PMD_IXGBE_LIBRARY dpdk_PMD_E1000_LIBRARY dpdk_PMD_BNXT_LIBRARY dpdk_PMD_RING_LIBRARY dpdk_PMD_CXGBE_LIBRARY dpdk_PMD_ENA_LIBRARY dpdk_PMD_ENIC_LIBRARY dpdk_PMD_NFP_LIBRARY dpdk_PMD_QEDE_LIBRARY dpdk_RING_LIBRARY dpdk_KVARGS_LIBRARY dpdk_MEMPOOL_LIBRARY dpdk_MEMPOOL_RING_LIBRARY dpdk_HASH_LIBRARY dpdk_CMDLINE_LIBRARY dpdk_MBUF_LIBRARY dpdk_CFGFILE_LIBRARY dpdk_EAL_LIBRARY dpdk_ETHDEV_LIBRARY dpdk_NET_LIBRARY dpdk_TIMER_LIBRARY dpdk_PCI_LIBRARY dpdk_BUS_PCI_LIBRARY dpdk_BUS_VDEV_LIBRARY dpdk_PMD_FM10K_LIBRARY dpdk_PMD_SFC_EFX_LIBRARY)
> CMake Error at cmake/SeastarDependencies.cmake:98 (find_package):
>   Could not find a configuration file for package "fmt" that is compatible
>   with requested version "5.0.0".
> 
>   The following configuration files were considered but not accepted:
> 
>     /usr/lib/cmake/fmt/fmt-config.cmake, version: 4.0.0
> 
> Call Stack (most recent call first):
>   CMakeLists.txt:310 (seastar_find_dependencies)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/proj/seastar/build/release/CMakeFiles/CMakeOutput.log".
> See also "/proj/seastar/build/release/CMakeFiles/CMakeError.log".
> Traceback (most recent call last):
>   File "./configure.py", line 226, in <module>
>     configure_mode(mode)
>   File "./configure.py", line 223, in configure_mode
>     subprocess.check_call(ARGS, shell=False, cwd=dir)
>   File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '-G', 'Ninja', '../..', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_C_COMPILER=gcc', '-DCMAKE_CXX_COMPILER=g++', '-DCMAKE_INSTALL_PREFIX=/usr/local', '-DSeastar_API_LEVEL=3', '-DSeastar_EXCLUDE_TESTS_FROM_ALL=no', '-DSeastar_EXCLUDE_APPS_FROM_ALL=no', '-DSeastar_EXCLUDE_DEMOS_FROM_ALL=no', '-DSeastar_CXX_FLAGS=', '-DSeastar_LD_FLAGS=', '-DSeastar_CXX_DIALECT=gnu++17', '-DSeastar_DPDK=no', '-DSeastar_DPDK_MACHINE=native', '-DSeastar_HWLOC=yes', '-DSeastar_ALLOC_FAILURE_INJECTION=DEFAULT', '-DSeastar_TASK_BACKTRACE=no', '-DSeastar_ALLOC_PAGE_SIZE=no', '-DSeastar_SPLIT_DWARF=no', '-DSeastar_HEAP_PROFILING=no', '-DSeastar_UNUSED_RESULT_ERROR=no']' returned non-zero exit status 1.

any insights on how to solve "Could NOT find dpdk"?

I mean, I know it sounds rather silly, but I was expecting to be able to build the project out of the box, using the instructions i readme. And those do not mention that I have to checkout dpdk manually, or something like this. So should I first checkout dpdk?

**Comment by mikhail-barg** [comment]
seems to be a duplicate of https://github.com/scylladb/scylla/issues/6229

**Comment by avikivity** [comment]
Seastar issues should be reported in this repository, not scylla.

**Comment by avikivity** [comment]
For dpdk, try `git submodule update --recursive`.

**Comment by mikhail-barg** [comment]
Thanks for the comment. I've found that I forgot to checkout submodules (would be great to have this in readme anyway), but doing so does not help `configure` to find dpdk. It seems that dpdk itself should also be built and probably installed. 

Anyway, I tried running `configure` with `--disable-dpdk` and it still mention that dpdk is not found, but then it does continue and fails with

> 
> CMake Error at cmake/SeastarDependencies.cmake:98 (find_package):
> Could not find a configuration file for package "fmt" that is compatible
> with requested version "5.0.0".
> 
> The following configuration files were considered but not accepted:
> 
> /usr/lib/cmake/fmt/fmt-config.cmake, version: 4.0.0

As in my original message. It seems that Ubuntu havs only 4.0.0 version of fmtlib-dev in it's repo. So one solution would be to checkout, build and install it from source (https://github.com/fmtlib/fmt.git) which is mentioned in the issue i've found in scylla repo.

After that `configure` does finis successfully, but then `ninja` build fails with 

> g++: error: unrecognized command line option ‘-fstack-clash-protection’; did you mean ‘-fstack-protector’?

which actually means that Ubuntu does not have a modern gcc supporting `-fstack-clash-protection` feature, and generally you have also build it from source, and then pass it via `--compiler` option to `confugure`.

Sadly this all is not covered in `install-dependencies` or at least readme )

**Comment by mikhail-barg** [comment]
now, after building new gcc, and building seastar with it, I'm getting errors similar to https://github.com/scylladb/seastar/issues/748: 

>../../include/seastar/core/future.hh:506:52: error: ‘struct seastar::future_state<seastar::syscall_result<int> >’ has no member named ‘uninitialized_get’; did you mean ‘uninitialized_wrapper’?
>  506 |             memmove(reinterpret_cast<char*>(&this->uninitialized_get())

**Comment by mikhail-barg** [comment]
Actually, I get really a lot of errors, and the first one seem to be this:

> In file included from ../../include/seastar/core/fair_queue.hh:24,
>                  from ../../src/core/fair_queue.cc:22:
> ../../include/seastar/core/shared_ptr.hh:190:32: error: ‘remove_const_t’ in namespace ‘std’ does not name a template type; did you mean ‘remove_const’?
>   190 |     using concrete_type = std::remove_const_t<T>;
>       |                                ^~~~~~~~~~~~~~
>       |                                remove_const
> ../../include/seastar/core/shared_ptr.hh:227:52: error: expected template-name before ‘<’ token
>   227 | struct lw_shared_ptr_accessors : std::conditional_t<
>       |                                                    ^

**Comment by avikivity** [comment]
It's best to list the first error, often the following ones are bogus.

As far as I can tell uninitialized_get() exists (and it compiles on my compiler, gcc 10.2), so likely some earlier error caused the failure.

**Comment by mikhail-barg** [comment]
Well, next thing to do is to apply this patch:

> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -28,6 +28,10 @@ list (APPEND CMAKE_MODULE_PATH
> 
>  include (Cooking OPTIONAL)
> 
> +set(CMAKE_CXX_STANDARD 17)
> +set(CMAKE_CXX_STANDARD_REQUIRED ON)
> +set(CMAKE_CXX_EXTENSIONS OFF)
> +

Because Ubuntu 18 has old CMake.

Then it's needed to install nettle (https://git.lysator.liu.se/nettle/nettle, https://ftp.gnu.org/gnu/nettle/) and GnuTLS (https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/).
