### PR TITLE
log: do not inherit formatter<seastar::log_level> from formatter<string_view>

### LINKED ISSUE #1189: log.cc doesn't build with fmt 7.1.3
On Fedora 34
```
$ rpm -qa | grep fmt
fmt-7.1.3-3.fc34.x86_64
fmt-devel-7.1.3-3.fc34.x86_64

$ grep -r FMT_VERSION /usr/include/fmt
/usr/include/fmt/core.h:#define FMT_VERSION 70103
```

```
FAILED: CMakeFiles/seastar.dir/src/util/log.cc.o 
/usr/bin/clang++ -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEFERRED_ACTION_REQUIRE_NOEXCEPT -DSEASTAR_ENABLE_ALLOC_FAILURE_INJECTION -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_SCHEDULING_GROUPS_COUNT=16 -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_TYPE_ERASE_MORE -I../../include -Igen/include -I../../src -Igen/src -O2 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Wno-error=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -std=gnu++20 -MD -MT CMakeFiles/seastar.dir/src/util/log.cc.o -MF CMakeFiles/seastar.dir/src/util/log.cc.o.d -o CMakeFiles/seastar.dir/src/util/log.cc.o -c ../../src/util/log.cc
../../src/util/log.cc:85:49: error: no matching member function for call to 'format'
            return formatter<std::string_view>::format(
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/fmt/core.h:1110:22: note: in instantiation of function template specialization 'fmt::formatter<seastar::log_level>::format<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>>' requested here
    ctx.advance_to(f.format(*static_cast<const T*>(arg), ctx));
                     ^
/usr/include/fmt/core.h:1096:21: note: in instantiation of function template specialization 'fmt::detail::value<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>>::format_custom_arg<seastar::log_level, fmt::formatter<seastar::log_level>>' requested here
    custom.format = format_custom_arg<
                    ^
/usr/include/fmt/core.h:1438:10: note: in instantiation of function template specialization 'fmt::detail::value<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>>::value<seastar::log_level>' requested here
  return check<T>(arg_mapper<Context>().map(val));
         ^
/usr/include/fmt/core.h:1587:23: note: in instantiation of function template specialization 'fmt::detail::make_arg<true, fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>, fmt::detail::type::custom_type, seastar::log_level, 0>' requested here
        data_{detail::make_arg<
                      ^
/usr/include/fmt/core.h:1626:10: note: in instantiation of member function 'fmt::format_arg_store<fmt::basic_format_context<fmt::detail::buffer_appender<char>, char>, seastar::log_level>::format_arg_store' requested here
  return {args...};
         ^
/usr/include/fmt/core.h:2004:28: note: in instantiation of function template specialization 'fmt::make_args_checked<seastar::log_level &, char [4], char>' requested here
  const auto& vargs = fmt::make_args_checked<Args...>(format_str, args...);
                           ^
../../src/util/log.cc:325:19: note: in instantiation of function template specialization 'fmt::format_to<seastar::internal::log_buf::inserter_iterator, char [4], seastar::log_level &, true>' requested here
        it = fmt::format_to(it, "{} ", level);
                  ^
/usr/include/fmt/format.h:3499:1: note: candidate function template not viable: no known conversion from 'const formatter<seastar::log_level, [2 * ...]>' to 'formatter<std::basic_string_view<char>, [2 * ...]>' for object argument
FMT_FORMAT_AS(detail::std_string_view<Char>, basic_string_view<Char>);
^
/usr/include/fmt/format.h:3485:10: note: expanded from macro 'FMT_FORMAT_AS'
    auto format(Type const& val, FormatContext& ctx) -> decltype(ctx.out()) { \
         ^
../../src/util/log.cc:89:45: error: no matching member function for call to 'format'
        return formatter<std::string_view>::format(name, ctx);
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/include/fmt/format.h:3499:1: note: candidate function template not viable: no known conversion from 'const formatter<seastar::log_level, [2 * ...]>' to 'formatter<std::basic_string_view<char>, [2 * ...]>' for object argument
FMT_FORMAT_AS(detail::std_string_view<Char>, basic_string_view<Char>);
^
/usr/include/fmt/format.h:3485:10: note: expanded from macro 'FMT_FORMAT_AS'
    auto format(Type const& val, FormatContext& ctx) -> decltype(ctx.out()) { \
         ^
2 errors generated.
```

Reverting dde522b1e24e06e72a72f33a9d0c2a94478a021d solves the issue for me.

### PR DESCRIPTION
**Pull request by tchaikov**
it turns out, in fmt v7.1.3, `formatter<std::string_view>::format()` is
not marked as const yet. the change which marked the formatters `const`
was introduced in
https://github.com/fmtlib/fmt/commit/bbd6ed5bc57adba7a3fc11804770e75299673761.

before that we cannot assume the constness of this method. so let's
just don't mark this format() const yet.

this change should address the FTBFS with fmt v7.1.3.

Fixes #1189
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
hi @bhalevy and @xemul , sorry for the regression, i tested with fmt v7.1.3 with debug build. the tree compiled, and tests passed.

**Comment by tchaikov** [comment]
for those who are interested, the change which change the formatter to `const` is at https://github.com/fmtlib/fmt/commit/bbd6ed5bc57adba7a3fc11804770e75299673761#diff-bdc6f79e8e9f5b4331d66fb785636a87d29f55cf729865e13925b4209424c878R3557

**Comment by bhalevy** [comment]
Don't we want to mark the method const conditionally for higher FMT_VERSION
that include https://github.com/fmtlib/fmt/commit/bbd6ed5bc57adba7a3fc11804770e75299673761?

**Comment by tchaikov** [comment]
> Don't we want to mark the method const conditionally for higher FMT_VERSION
> that include [fmtlib/fmt@bbd6ed5](https://github.com/fmtlib/fmt/commit/bbd6ed5bc57adba7a3fc11804770e75299673761)?

@bhalevy hi Benny, thanks for your review. but i don't think that is worth the complexity. so in this change, i just rewrite the class so it is not a derived class of `formatter<std::string_view>` anymore. could you take another look?

**Review by bhalevy — APPROVED** [review]
lgtm
