### ISSUE TITLE
Ubuntu dependency

### ISSUE THREAD

**Issue by tbenthompson** [scylladb/seastar#62]
Hello,

Building on Ubuntu 15.04, I needed to install the "xfslibs-dev" package. Otherwise, I got the error:
FAILED: g++ -MMD -MT build/debug/core/reactor.o -MF build/debug/core/reactor.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined  -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -I build/debug/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE   -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -c -o build/debug/core/reactor.o core/reactor.cc
core/reactor.cc:51:23: fatal error: xfs/linux.h: No such file or directory
 #include <xfs/linux.h>

Just FYI since it's not in the dependencies list in the README.

**Comment by dmarti** [comment]
The 15.04 build instructions seem to be simpler than 14.04 because you don't have to add the gcc 4.9 apt repository separately.  The following is my draft of a section on how to build on 15.04 for the README:

### Building seastar on Ubuntu 15.04

Install required packages:
```
sudo apt-get install libaio-dev ninja-build ragel libhwloc-dev libnuma-dev libpciaccess-dev libcrypto++-dev libboost-all-dev libxen-dev libxml2-dev xfslibs-dev g++
```

To compile Seastar on Ubuntu 15.04
```
./configure.py
ninja -j 2
```

(The build command is installed as `ninja` on Ubuntu, not `ninja-build` as on Fedora.)

**Comment by nyh** [comment]
On Wed, Oct 14, 2015 at 2:34 AM, Don Marti <notifications@github.com> wrote:

> To compile Seastar on Ubuntu 15.04
>
> ./configure.py
> ninja -j 2
>
>
Note that unlike "make -j" where if you don't give it a parameter it uses a
crazy default (basically, run as many as jobs as it can in parallel - even
a hundred), ninja actually has a sensible default (perhaps the number of
hardware threads times 1.5?), so often just "ninja" works well (no need for
"-j", it's the default). If you have more than 2 cores, not giving "-j2"
will make your compilation considerably faster, which is, sadly, very
important for Seastar compilation, because it so slow you need to take
advantage of every available CPU...

On the other hand, there is a second problem: Seastar compilation is not
only slow, it also takes a lot of memory, so some unbalanced systems (e.g.,
4 CPUs with just 1 GB of memory) cannot cope with the default 6 parallel
compilations in the 4-cpu case and run out of memory during compilation. In
that case an explicit thread number, like your "-j 2", is needed.

I don't know how to shorten all of this to one sentence of the README, but
I'm worried that telling people to use "ninja -j 2" in a day of age when
even phones have 8 cpus, will just cause people to needlessly experience
even longer compilations than our already very long compilation.

>  (The build command is installed as ninja on Ubuntu, not ninja-build as
> on Fedora.)
>

Life is too short to type "ninja-build" on every compilation. Fedora users
should do what I did - create a symbolic link from ninja-build to "ninja"
:-)

**Comment by dmarti** [comment]
My Ubuntu 15.04 VM with 2GB of memory and 2 CPUs fails with
`virtual memory exhausted: Cannot allocate memory` if I just run `ninja` or `ninja -j 2`.  On that VM I need to do `-j 1`.

**Comment by banks** [comment]
FWIW the dependency is missing in the docker file too: https://github.com/scylladb/seastar/pull/71

**Comment by tchaikov** [comment]
`xfslibs-dev` is now included by `install-dependencies.sh`. closing.
