### ISSUE TITLE
Cannot build on Xubuntu 16.04

### ISSUE THREAD

**Issue by armandjordaan** [scylladb/seastar#260]
Hi,

I hope you can help, I have some trouble building on Xubuntu 16.04:

`??@??-VirtualBox:~/Projects/seastar/seastar$ ./configure.py --compiler=g++-5`
`Notice: -fsanitize=vptr is broken, disabling; some debug mode tests are bypassed.`

and then when I build:

`??@??-VirtualBox:~/Projects/seastar/seastar$ ninja`
`[8/336] CXX build/debug/tests/tcp_test.o`
`FAILED: g++-5 -MD -MT build/debug/tests/tcp_test.o -MF build/debug/tests/tcp_test.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DASAN_ENABLED -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -I build/debug/gen -I build/debug/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error-deprecated -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -Ifmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/debug/tests/tcp_test.o tests/tcp_test.cc
In file included from ./core/reactor.hh:64:0,
                 from ./net/net.hh:25,
                 from ./net/arp.hh:26,
                 from ./net/ip.hh:37,
                 from tests/tcp_test.cc:22:
./core/file.hh: In member function ‘future<temporary_buffer<char_type> > file::read_maybe_eof(uint64_t, size_t, const io_priority_class&)’:
./core/file.hh:629:79: error: no matching function for call to ‘align_up(size_t&, uint64_t)’
                memory_dma_alignment(), align_up(len, disk_read_dma_alignment()));
                                                                               ^
In file included from ./core/file.hh:28:0,
                 from ./core/reactor.hh:64,
                 from ./net/net.hh:25,
                 from ./net/arp.hh:26,
                 from ./net/ip.hh:37,
                 from tests/tcp_test.cc:22:
./core/align.hh:30:3: note: candidate: template<class T> constexpr T align_up(T, T)
 T align_up(T v, T align) {
   ^
./core/align.hh:30:3: note:   template argument deduction/substitution failed:
In file included from ./core/reactor.hh:64:0,
                 from ./net/net.hh:25,
                 from ./net/arp.hh:26,
                 from ./net/ip.hh:37,
                 from tests/tcp_test.cc:22:
./core/file.hh:629:79: note:   deduced conflicting types for parameter ‘T’ (‘unsigned int’ and ‘long long unsigned int’)
                memory_dma_alignment(), align_up(len, disk_read_dma_alignment()));
                                                                               ^
In file included from ./core/file.hh:28:0,
                 from ./core/reactor.hh:64,
                 from ./net/net.hh:25,
                 from ./net/arp.hh:26,
                 from ./net/ip.hh:37,
                 from tests/tcp_test.cc:22:
./core/align.hh:36:4: note: candidate: template<class T> constexpr T* align_up(T*, size_t)
 T* align_up(T* v, size_t align) {
    ^
./core/align.hh:36:4: note:   template argument deduction/substitution failed:
In file included from ./core/reactor.hh:64:0,
                 from ./net/net.hh:25,
                 from ./net/arp.hh:26,
                 from ./net/ip.hh:37,
                 from tests/tcp_test.cc:22:
./core/file.hh:629:79: note:   mismatched types ‘T*’ and ‘unsigned int’
                memory_dma_alignment(), align_up(len, disk_read_dma_alignment()));
                                                                               ^
In file included from ./net/ip.hh:38:0,
                 from tests/tcp_test.cc:22:
./net/ip_checksum.hh: At global scope:
./net/ip_checksum.hh:35:5: error: expected unqualified-id before ‘__int128’
     __int128 csum = 0;
     ^
./net/ip_checksum.hh: In member function ‘void net::checksummer::sum(uint8_t)’:
./net/ip_checksum.hh:41:13: error: ‘csum’ was not declared in this scope
             csum += data << 8;
             ^
./net/ip_checksum.hh:43:13: error: ‘csum’ was not declared in this scope
             csum += data;
             ^
./net/ip_checksum.hh: In member function ‘void net::checksummer::sum(uint16_t)’:
./net/ip_checksum.hh:52:13: error: ‘csum’ was not declared in this scope
             csum += data;
             ^
./net/ip_checksum.hh: In member function ‘void net::checksummer::sum(uint32_t)’:
./net/ip_checksum.hh:60:13: error: ‘csum’ was not declared in this scope
             csum += data;
             ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-error-deprecated’ [-Werror]
cc1plus: all warnings being treated as errors`

Any help will be appreciated.

**Comment by armandjordaan** [comment]
OK. I feel a bit silly now. I was building on a 32bit system. On a 64bit system it builds just fine.
