### PR TITLE
build: name OpenSSL among seastar.pc's private requirements

### PR DESCRIPTION
**Pull request by avikivity**
Seastar's OpenSSL TLS and crypto backend links libssl and libcrypto, but
`seastar.pc` never said so, so linking a static libseastar through pkg-config
ended in

```
libseastar.a(crypto_openssl.cc.o): in function `seastar::internal::crypto::(anonymous namespace)::openssl_md5_finalize(unsigned char*)':
crypto_openssl.cc:107: undefined reference to `EVP_DigestFinal_ex'
crypto_openssl.cc:120: undefined reference to `EVP_MD_CTX_free'
```

Add them to `Requires.private`, conditional on `Seastar_OPENSSL` the way
liburing already is.

Only static consumers were affected: a shared libseastar carries its own
`DT_NEEDED` entries, and pkg-config hands `Libs.private` and
`Requires.private` out only when asked for a static link. Found while adding an
installed-consumer build test in #3548, which is the first thing in the tree to
link against the installed `seastar.pc`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by avikivity** [comment]
Regression coverage for this is in #3679, which adds `tests/consumer/` — a
standalone project that builds an application against an *installed* Seastar
through both published channels — and a CI job that runs it against a static
build. The pkg-config consumer there reads the `STATIC_` variables from
`pkg_check_modules`, so `Requires.private` is exercised rather than ignored.

It could not go in this PR: the job is red without this fix (and without
#3677), so the test necessarily lands on top of the two fixes rather than
alongside them. #3679 carries both commits for that reason, and they drop out
when these merge.

Confirmed the coverage bites: with #3679 in place, dropping `libssl` and
`libcrypto` from `Requires.private` reproduces the original failure —
`consumer_pkgconfig` fails to link with undefined `EVP_MD_CTX_new` / `EVP_md5`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by avikivity** [comment]
Closing in favour of #3679, which now carries both fixes together with the
installed-consumer test that covers them. Splitting them across three PRs meant
the test could only ever land after the fixes — the job it adds is red without
them — so there was no arrangement in which either fix merged with its own
coverage. One PR it is.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
