### ISSUE TITLE
Failure to build on Ubuntu 15.10 "‘system_category’ is not a member of ‘std’"

### ISSUE THREAD

**Issue by jaypipes** [scylladb/seastar#121]
Building on Ubuntu 15.10, g++ is 5.2.1, but I have installed g++-4.9 and associated tooling and successfully run ./configure.py --compiler=g++-4.9 as the build instructions for Ubuntu 14.04 indicate.

I'm getting a failure when building rpc_test.o:

```
jaypipes@uberbox:~/repos/seastar$ ninja 
[44/266] CXX build/release/tests/rpc_test.o
FAILED: g++-4.9 -MMD -MT build/release/tests/rpc_test.o -MF build/release/tests/rpc_test.o.d -O2 -I build/release/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -Wno-overloaded-virtual -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -c -o build/release/tests/rpc_test.o tests/rpc_test.cc
In file included from tests/rpc_test.cc:23:0:
tests/loopback_socket.hh: In member function ‘future<> loopback_buffer::push(temporary_buffer<char>&&)’:
tests/loopback_socket.hh:38:44: error: ‘system_error’ is not a member of ‘std’
             return make_exception_future<>(std::system_error(EPIPE, std::system_category()));
                                            ^
tests/loopback_socket.hh:38:69: error: ‘system_category’ is not a member of ‘std’
             return make_exception_future<>(std::system_error(EPIPE, std::system_category()));
                                                                     ^
tests/loopback_socket.hh: In member function ‘future<temporary_buffer<char> > loopback_buffer::pop()’:
tests/loopback_socket.hh:44:66: error: ‘system_error’ is not a member of ‘std’
             return make_exception_future<temporary_buffer<char>>(std::system_error(EPIPE, std::system_category()));
                                                                  ^
tests/loopback_socket.hh:44:91: error: ‘system_category’ is not a member of ‘std’
             return make_exception_future<temporary_buffer<char>>(std::system_error(EPIPE, std::system_category()));
                                                                                           ^
tests/loopback_socket.hh: In member function ‘void loopback_buffer::shutdown()’:
tests/loopback_socket.hh:50:42: error: ‘system_error’ is not a member of ‘std’
         _q.abort(std::make_exception_ptr(std::system_error(EPIPE, std::system_category())));
                                          ^
tests/loopback_socket.hh:50:67: error: ‘system_category’ is not a member of ‘std’
         _q.abort(std::make_exception_ptr(std::system_error(EPIPE, std::system_category())));
                                                                   ^
tests/loopback_socket.hh: In member function ‘virtual void loopback_server_socket_impl::abort_accept()’:
tests/loopback_socket.hh:141:49: error: ‘system_error’ is not a member of ‘std’
         _pending->abort(std::make_exception_ptr(std::system_error(ECONNABORTED, std::system_category())));
                                                 ^
tests/loopback_socket.hh:141:81: error: ‘system_category’ is not a member of ‘std’
         _pending->abort(std::make_exception_ptr(std::system_error(ECONNABORTED, std::system_category())));
                                                                                 ^
[44/266] CXX build/release/tests/rpc.o
```

Any ideas? Perhaps a conflicting version of boost headers for the std namespace or something?

**Comment by jaypipes** [comment]
BTW, if I try to compile with g++-5.2, I get the following:

```
jaypipes@uberbox:~/repos/seastar$ g++ --version
g++ (Ubuntu 5.2.1-23ubuntu1~15.10) 5.2.1 20151028
...
jaypipes@uberbox:~/repos/seastar$ ./configure.py --compiler=g++
-fsanitize=vptr is broken, disabling
```

**Comment by jaypipes** [comment]
A few details about my system, in case it's useful:

```
jaypipes@uberbox:~/repos/seastar$ dpkg -l | grep libboost-dev
ii  libboost-dev:amd64                                   1.58.0.0ubuntu1                            amd64        Boost C++ Libraries development files (default version)
jaypipes@uberbox:~/repos/seastar$ git log --oneline | head -n1
906b562 rpc: prepare some more for feature negotiation
jaypipes@uberbox:~/repos/seastar$ uname -r
4.2.0-30-generic
```

**Comment by jaypipes** [comment]
Confirmed that d9f5836 fixes the issue. Thanks all! There is an additional failure in building, but I'll file another issue for that.
